version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: Telegram_Fliter_Bot

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db